//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMetier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        public int Id { get; set; }
        public string NameProduit { get; set; }
        public string DescriptionProduit { get; set; }
        public int PriceProduit { get; set; }
        public Nullable<int> QteMinimal { get; set; }
    }
}
